models:
  - name: fct_credit_risk
    description: >
      The transactional fact table for credit risk. 
      Grain: One row per asset_id.
    columns:
      - name: asset_id
        description: Surrogate key (Hash of created_at + buyer_id + value).
        tests:
          - unique
          - not_null

      - name: provision_rate
        description: >
          The calculated risk percentage based on Status and Rating.
          Logic: Settled (0.0), Defaulted (1.0), or Rated (0.01 - 0.40).
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1.0

      - name: collection_status
        description: Normalized status of the loan.
        tests:
          - accepted_values:
              values: ["Settled", "Active", "Defaulted", "Canceled"]

  - name: stg_assets
    columns:
      - name: face_value
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
